
[tool.black]
    line-length = 110
    target-version = ['py37', 'py38', 'py39']
    include = '\.pyi?$'
    skip-string-normalization = true

[tool.pytest.ini_options]
minversion = "6.0"
#addopts = "-ra -q"
testpaths = [
    "tests"
]