model_args:
  dropout: 0.3
  ff_size: 4096
  hid_size: 1024
  n_heads: 16
  enc_layers: 6
  dec_layers: 6
  src_vocab: 8000
  tgt_vocab: 8000
  tied_emb: three-way
model_type: tfmnmt
optim:
  args:
    betas:
    - 0.9
    - 0.98
    eps: 1.0e-09
    label_smoothing: 0.1
    lr: 0.2
    warmup_steps: 8000
    constant: 2
  name: ADAM
prep:
  max_types: 8000
  pieces: bpe
  shared_vocab: true
  src_len: 256
  tgt_len: 256
  train_src: data/train.src
  train_tgt: data/train.tgt
  truncate: true
  valid_src: data/valid.src
  valid_tgt: data/valid.tgt
  mono_src: []
  mono_tgt: []
tester:
  decoder:
    tune:
      trials: 6
      tune_src: data/valid.src
      tune_ref: data/valid.tgt
      beam_size: [1, 4, 8]
      ensemble: [1, 5, 10]
      lp_alpha: [0.0, 0.4, 0.6, 1.0]
      suggested:
        - 1, 1, 0.0
        - 1, 1, 0.6
        - 4, 1, 0.0
        - 4, 1, 0.6
        - 1, 5, 0.0
        - 1, 5, 0.6
        - 4, 5, 0.0
        - 4, 5, 0.6
        - 1, 10, 0.0
        - 1, 10, 0.6
        - 4, 10, 0.0
        - 4, 10, 0.6
  suit:
    valid:
    - data/valid.src
    - data/valid.tgt
trainer:
  init_args:
    chunk_size: 10
  batch_size: 2600
  check_point: 1000
  keep_models: 10
  steps: 200000
updated_at: '2019-03-09T21:15:33.707183'
seed: 12345