
== RTG Serve

RTG model can be served using Flask Server.

=== Flask Installation

[source, commandline]
----
$ pip install rtg[serve]
----

Flask has its own set of dependencies unrelated to the core functionality, hence, not installed when installing `rtg`.

=== Running

[source,commandline]
----
$ python -m rtg.serve -h  # rtg-serve
usage: rtg.serve [-h] [-d] [-p PORT] [-ho HOST] [-msl MAX_SRC_LEN] exp_dir

Deploy an RTG model to a RESTful server

positional arguments:
  exp_dir               Experiment directory

optional arguments:
  -h, --help            show this help message and exit
  -d, --debug           Run Flask server in debug mode (default: False)
  -p PORT, --port PORT  port to run server on (default: 6060)
  -ho HOST, --host HOST
                        Host address to bind. (default: 0.0.0.0)
  -b BASE, --base BASE  Base prefix path for all the URLs (default: None)
  -msl MAX_SRC_LEN, --max-src-len MAX_SRC_LEN
                        max source len; longer seqs will be truncated
                        (default: 250)
----


To launch a service for `runs/001-tfm` experiment, run `python -m rtg.serve -d runs/001-tfm`
To use basepath of `/v1`: `python -m rtg.serve -d runs/001-tfm -b /v1`


It prints :
`* Running on http://0.0.0.0:6060/ (Press CTRL+C to quit)`

Currently only `/translate` API is supported. It accepts both `GET` with query params and `POST` with form params.

NOTE: batch decoding is yet to be supported. The current decoder decodes only one sentence at a time.

An example POST request:
----
 curl --data "source=Comment allez-vous?" --data "source=Bonne journée" http://localhost:6060/translate

----
[source,json]
----

{
  "source": [
    "Comment allez-vous?",
    "Bonne journée"
  ],
  "translation": [
    "How are you?",
    "Have a nice day"
  ]
}
----
You can also request like GET method as `http://localhost:6060/translate?source=text1&source=text2`
after properly URL encoding the `text1` `text2`. This should only be used for quick testing in your web browser.


**Production Deployment**
Please use uWSGI for production deployment.
If you dont already have uWSGI, you may install it via conda by running `conda install -c conda-forge uwsgi`.

[source,bash]
----
uwsgi --http 127.0.0.1:5000 --module rtg.serve.app:app --pyargv "<path-to-exp-dir>"

# or using a .ini file
uwsgi --ini examples/uwsgi.ini
----
Where the `uwsgi.ini` has the following info:

[source,ini]
----
[uwsgi]
http = 0.0.0.0:6060
module = rtg.serve.app:app
pyargv = /full/path/<path-to-exp-dir> -b /v1
master = true
processes = 1
stats = 127.0.0.1:9191
----

Note that `<path-to-exp-dir>` is expected to be a valid path to Experiment dir, it maybe obtained using `rtg-export` tool.





